### ISSUE TITLE
[firefly-iii] Overrides user, forces embedded db charts or sqlite

### ISSUE THREAD

**Issue by disconn3ct** [geek-cookbook/charts#23]
### Helm chart name

firefly-iii

### Helm chart version

0.3.0

### Container name

fireflyiii/core

### Container tag

version-6.0.20

### Description

https://github.com/geek-cookbook/charts/blob/main/charts/stable/firefly-iii/templates/common.tpl#L1 forces DB_CONNECTION to use the embedded databases.
https://github.com/geek-cookbook/charts/blob/main/charts/stable/firefly-iii/values.yaml#L161 indicates it is user-accessible

### Expected result

Don't overwrite incoming values

### Helm values to reproduce

```YAML
env:
  DB_CONNECTION: "pgsql"
  DB_HOST: "host"
postgresql:
  enabled: false
mariadb:
  enabled: false
```
